config/routes.rb
Yakut::Application.routes.draw do
  devise_for :admins, controllers: {sessions: 'hq/sessions'}, path: 'hq',
             path_names: {sign_in: 'login', sign_out: 'logout', password: 'secret',
                          confirmation: 'verification'}
  devise_for :users
  root to: 'welcome#index'
  namespace :hq do
      resources :dashboard do
        get :tables, on: :collection
        get :form, on: :collection
      end
  end

  

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user.rb
class User < ActiveRecord::Base
  extend Enumerize

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  enumerize :role, in: {user: 1, teacher: 2}, default: :user
end

app/controllers/application_controller.rb
require 'application_responder'

class ApplicationController < ActionController::Base
  before_filter :set_user_time_zone


  self.responder = ApplicationResponder
  respond_to :html, :json
  WillPaginate.per_page = 10

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  protected
  def set_user_time_zone
    Time.zone = current_user.time_zone if user_signed_in? && current_user.time_zone.present?
  end



  def devise_parameter_sanitizer
    if resource_class == User
      User::ParameterSanitizer.new(User, :user, params)
    else
      super # Use the default one
    end
  end


  def after_sign_in_path_for(resource_or_scope)
    if current_user
      super
    else
      hq_dashboard_index_path
    end
  end
end

app/controllers/hq/application_controller.rb
require 'application_responder'

class Hq::ApplicationController < ActionController::Base
  add_breadcrumb I18n.t('navbar.root'), :hq_dashboard_index_path
  before_action :authenticate_admin!
  self.responder = ApplicationResponder
  respond_to :html, :json
end

app/controllers/hq/base_controller.rb
require 'application_responder'

class Hq::BaseController < ActionController::Base
  before_action :authenticate_admin!
  self.responder = ApplicationResponder
  respond_to :html, :json
end

app/controllers/hq/dashboard_controller.rb
class Hq::DashboardController < Hq::ApplicationController
  def index

  end
end

app/controllers/hq/sessions_controller.rb
class Hq::SessionsController < Devise::SessionsController

  layout 'login'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def page(title, id)
    @page_id = id
    content_for :title do
      title
    end
  end

  def launcher_active(page)
    @page_id == page ? {class:'active'} : {}
  end

end

app/views/hq/dashboard/form.html.haml
- page 'Forms', 'forms'

.panel.panel-default
  .panel-heading
    %i.icon-edit.icon-large
    Form Default
  .panel-body

    %form

      %fieldset
        %legend Default Inputs

        .form-group
          %label.control-label Text field
          %input.form-control{placeholder: 'Enter username', type: 'text'}/

        .form-group
          %label.control-label Password field
          %input.form-control{placeholder: 'Enter password', type: 'password'}/

        .form-group
          %label.control-label Input field with help
          %input.form-control{placeholder: '.help-block'}/
          %p.help-block Example block-level help text here.

        .form-group
          %label.control-label Disabled field
          %input.form-control{placeholder: 'This is field is disabled!', disabled: true}/

        .form-group
          %label.control-label Tooltip field
          %input.form-control{data: {toggle: 'tooltip'}, title: 'Input tips here', placeholder: 'This is field is disabled!'}/

        .form-group
          %label.control-label Textarea field
          %textarea.form-control{rows: 4}

        .form-group
          %label.control-label File input
          %input{type: 'file'}

        .form-group
          %label.control-label Large field
          %input.form-control.input-lg{type: 'text', placeholder: '.input-lg'}/

        .form-group
          %label.control-label Small field
          %input.form-control.input-sm{type: 'text', placeholder: '.input-sm'}/

        .form-group.row
          .col-lg-2
            %label.control-label Column sizing
            %input.form-control{type: 'text', placeholder: '.col-lg-2'}/
          .col-lg-3
            %label.control-label Column sizing
            %input.form-control{type: 'text', placeholder: '.col-lg-3'}/
          .col-lg-7
            %label.control-label Column sizing
            %input.form-control{type: 'text', placeholder: '.col-lg-7'}/

      %fieldset
        %legend Input Validation States

        .form-group.has-warning
          %label.control-label Input field with help
          %input.form-control{placeholder: '.has-warning'}/
          %p.help-block Example block-level help text here.

        .form-group.has-error
          %label.control-label Input field with help
          %input.form-control{placeholder: '.has-error'}/
          %p.help-block Example block-level help text here.

        .form-group.has-success
          %label.control-label Input field with help
          %input.form-control{placeholder: '.has-success'}/
          %p.help-block Example block-level help text here.

      %fieldset
        %legend Checkboxes and radios

        .form-group
          %label.control-label Checkbox
          .checkbox
            %input{type: 'checkbox', value: ''}/
            Option one is this and that&mdash;be sure to include why it's great

        .form-group
          %label.control-label Inline checkbox
          %br/
          .checkbox-inline
            %input{type: 'checkbox', value: ''}/
            1
          .checkbox-inline
            %input{type: 'checkbox', value: ''}/
            2
          .checkbox-inline
            %input{type: 'checkbox', value: ''}/
            3

        .form-group
          %label.control-label Radio
          .radio
            %input{type: 'radio', name:'options_radio', value: 'option1', checked: true}
            Option one is this and that&mdash;be sure to include why it's great

            %br/

            %input{type: 'radio', name:'options_radio', value: 'option2', checked: true}
            Option two can be something else and selecting it will deselect option one

      %fieldset
        %legend Selects

        .form-group
          %label.control-label Single select
          %select.form-control
            %option 1
            %option 2
            %option 3
            %option 4
            %option 5

        .form-group
          %label.control-label Multiple select
          %select.form-control{multiple: true}
            %option 1
            %option 2
            %option 3
            %option 4
            %option 5

      .form-actions
        %button.btn.btn-default{:type => 'submit'} Submit
        %a.btn{href: '#'} Cancel

.panel.panel-default
  .panel-heading
    %i.icon-edit.icon-large
    Form Horizontal
  .panel-body

    %form.form-horizontal

      %fieldset
        %legend Default inputs

        .form-group
          %label.col-lg-2.control-label Text field
          .col-lg-10
            %input.form-control{placeholder: 'Enter username', type: 'text'}/

        .form-group
          %label.col-lg-2.control-label Password field
          .col-lg-10
            %input.form-control{placeholder: 'Enter password', type: 'password'}/

        .form-group
          %label.col-lg-2.control-label Input field with help
          .col-lg-10
            %input.form-control{placeholder: '.help-block'}/
            %p.help-block Example block-level help text here.%fieldset

        %legend Validation inputs

        .form-group.has-warning
          %label.col-lg-2.control-label Text field
          .col-lg-10
            %input.form-control{placeholder: 'Enter username', type: 'text'}/

        .form-group.has-error
          %label.col-lg-2.control-label Password field
          .col-lg-10
            %input.form-control{placeholder: 'Enter password', type: 'password'}/

        .form-group.has-success
          %label.col-lg-2.control-label Input field with help
          .col-lg-10
            %input.form-control{placeholder: '.help-block'}/
            %p.help-block Example block-level help text here.

      .form-actions
        %button.btn.btn-default{:type => 'submit'} Save
        %a.btn{href: '#'} Cancel

.panel.panel-default
  .panel-heading
    %i.icon-edit.icon-large
    Knob Inputs
  .panel-body.text-center
    %input.knob{type: 'text', value: '75', data: {width: 150, height: 150}}/
    %input.knob{type: 'text', value: '100', data: {fgColor: '#16a085', width: 150, height: 150}}/
    %input.knob{type: 'text', value: '200', data: {fgColor: '#7f8c8d', width: 150, height: 150}}/

app/views/hq/dashboard/index.html.haml
%h1= "Hi #{current_admin.email}"
= link_to 'Sign out', destroy_admin_session_path, class: 'btn btn-large', method: :delete

app/views/hq/dashboard/tables.html.haml
- page 'Tables', 'tables'

- content_for :toolbar do
  .btn-group
    %a.btn{href: '#', data: {toggle: 'toolbar-tooltip'}, title: 'Building'}
      %i.icon-building
    %a.btn{href: '#', data: {toggle: 'toolbar-tooltip'}, title: 'Laptop'}
      %i.icon-laptop
    %a.btn{href: '#', data: {toggle: 'toolbar-tooltip'}, title: 'Calendar'}
      %i.icon-calendar
      %span.badge 3
    %a.btn{href: '#', data: {toggle: 'toolbar-tooltip'}, title: 'Lemon'}
      %i.icon-lemon

.panel.panel-default.grid

  .panel-heading
    %i.icon-table.icon-large
    Default Table

    .panel-tools
      .btn-group
        %a.btn{href: '#'}
          %i.icon-wrench
          Settings
        %a.btn{href: '#'}
          %i.icon-filter
          Filters
        %a.btn{href: '#', data: {toggle: 'toolbar-tooltip'}, title: 'Reload'}
          %i.icon-refresh
      .badge 3 record

  .panel-body.filters
    .row
      .col-md-9
        Add your custom filters here...
      .col-md-3
        .input-group
          %input.form-control{placeholder: 'Quick search...', type: 'text'}/
          %span.input-group-btn
            %button.btn{type: 'button'}
              %i.icon-search

  %table.table
    %thead
      %tr
        %th #
        %th First Name
        %th Last Name
        %th Username
        %th.actions
          Actions
    %tbody
      %tr.success
        %td 1
        %td Mark
        %td Otto
        %td @mdo
        %td.action
          %a.btn.btn-success{href: '#', data: {toggle: 'tooltip'}, title: 'Zoom'}
            %i.icon-zoom-in
          %a.btn.btn-info{href: '#'}
            %i.icon-edit
          %a.btn.btn-danger{href: '#'}
            %i.icon-trash
      %tr.danger
        %td 2
        %td Jacob
        %td Thornton
        %td @fat
        %td.action
          %a.btn.btn-success{href: '#', data: {toggle: 'tooltip'}, title: 'Zoom'}
            %i.icon-zoom-in
          %a.btn.btn-info{href: '#'}
            %i.icon-edit
          %a.btn.btn-danger{href: '#'}
            %i.icon-trash
      %tr.warning
        %td 3
        %td Larry
        %td the Bird
        %td @twitter
        %td.action
          %a.btn.btn-success{href: '#', data: {toggle: 'tooltip'}, title: 'Zoom'}
            %i.icon-zoom-in
          %a.btn.btn-info{href: '#'}
            %i.icon-edit
          %a.btn.btn-danger{href: '#'}
            %i.icon-trash
      %tr.active
        %td 4
        %td Mark
        %td Otto
        %td @mdo
        %td.action
          %a.btn.btn-success{href: '#', data: {toggle: 'tooltip'}, title: 'Zoom'}
            %i.icon-zoom-in
          %a.btn.btn-info{href: '#'}
            %i.icon-edit
          %a.btn.btn-danger{href: '#'}
            %i.icon-trash
      %tr.disabled
        %td 5
        %td Jacob
        %td Thornton
        %td @fat
        %td.action
          %a.btn.btn-success{href: '#', data: {toggle: 'tooltip'}, title: 'Zoom'}
            %i.icon-zoom-in
          %a.btn.btn-info{href: '#'}
            %i.icon-edit
          %a.btn.btn-danger{href: '#'}
            %i.icon-trash
      %tr
        %td 6
        %td Larry
        %td the Bird
        %td @twitter
        %td.action
          %a.btn.btn-success{href: '#', data: {toggle: 'tooltip'}, title: 'Zoom'}
            %i.icon-zoom-in
          %a.btn.btn-info{href: '#'}
            %i.icon-edit
          %a.btn.btn-danger{href: '#'}
            %i.icon-trash
      %tr
        %td 7
        %td Jacob
        %td Thornton
        %td @fat
        %td.action
          %a.btn.btn-success{href: '#', data: {toggle: 'tooltip'}, title: 'Zoom'}
            %i.icon-zoom-in
          %a.btn.btn-info{href: '#'}
            %i.icon-edit
          %a.btn.btn-danger{href: '#'}
            %i.icon-trash
      %tr
        %td 8
        %td Larry
        %td the Bird
        %td @twitter
        %td.action
          %a.btn.btn-success{href: '#', data: {toggle: 'tooltip'}, title: 'Zoom'}
            %i.icon-zoom-in
          %a.btn.btn-info{href: '#'}
            %i.icon-edit
          %a.btn.btn-danger{href: '#'}
            %i.icon-trash
      %tr
        %td 9
        %td Mark
        %td Otto
        %td @mdo
        %td.action
          %a.btn.btn-success{href: '#', data: {toggle: 'tooltip'}, title: 'Zoom'}
            %i.icon-zoom-in
          %a.btn.btn-info{href: '#'}
            %i.icon-edit
          %a.btn.btn-danger{href: '#'}
            %i.icon-trash
      %tr
        %td 10
        %td Jacob
        %td Thornton
        %td @fat
        %td.action
          %a.btn.btn-success{href: '#', data: {toggle: 'tooltip'}, title: 'Zoom'}
            %i.icon-zoom-in
          %a.btn.btn-info{href: '#'}
            %i.icon-edit
          %a.btn.btn-danger{href: '#'}
            %i.icon-trash

  .panel-footer
    %ul.pagination.pagination-sm
      %li
        %a{:href => '#'} «
      %li.active
        %a{:href => '#'} 1
      %li
        %a{:href => '#'} 2
      %li
        %a{:href => '#'} 3
      %li
        %a{:href => '#'} 4
      %li
        %a{:href => '#'} 5
      %li
        %a{:href => '#'} 6
      %li
        %a{:href => '#'} 7
      %li
        %a{:href => '#'} 8
      %li
        %a{:href => '#'} »
    .pull-right
      Showing 1 to 10 of 32 entries

.panel.panel-default.grid
  .panel-heading
    %i.icon-table.icon-large
    Padding Table

  %table.table
    %thead
      %tr
        %th #
        %th First Name
        %th Last Name
        %th Username
    %tbody
      %tr
        %td 1
        %td Mark
        %td Otto
        %td @mdo
      %tr
        %td 2
        %td Jacob
        %td Thornton
        %td @fat
      %tr
        %td 3
        %td Larry
        %td the Bird
        %td @twitter

.panel.panel-default.grid
  .panel-heading
    %i.icon-table.icon-large
    Bordered Table
  .panel-body
    %table.table.table-bordered
      %thead
        %tr
          %th #
          %th First Name
          %th Last Name
          %th Username
      %tbody
        %tr
          %td 1
          %td Mark
          %td Otto
          %td @mdo
        %tr
          %td 2
          %td Jacob
          %td Thornton
          %td @fat
        %tr
          %td 3
          %td Larry
          %td the Bird
          %td @twitter


.panel.panel-default.grid
  .panel-heading
    %i.icon-table.icon-large
    Condensed Table
  %table.table.table-condensed
    %thead
      %tr
        %th #
        %th First Name
        %th Last Name
        %th Username
    %tbody
      %tr
        %td 1
        %td Mark
        %td Otto
        %td @mdo
      %tr
        %td 2
        %td Jacob
        %td Thornton
        %td @fat
      %tr
        %td 3
        %td Larry
        %td the Bird
        %td @twitter

app/views/layouts/application.html.haml
!!! 5
/[if IE 8]      <html class="no-js lt-ie10 lt-ie9" lang="en-us">
/[if IE 9]      <html class="no-js lt-ie10 lt-ie9" lang="en-us">
/[if lt IE 10]  <html class="no-js lt-ie10" lang="en-us">
%html{lang: 'en', class: 'no-js'}
  %head
    %title= yield :title
    %meta(http-equiv="content-type" content="text/html" charset="utf-8")
    %meta(http-equiv="x-ua-compatible" content="ie=edge,chrome=1")
    %meta(name="description" content="")
    %meta(name="author" content="")
    %meta{content: 'initial-scale=1.0,user-scalable=no,maximum-scale=1,width=device-width', name: 'viewport'}
    %meta(name="viewport" content="initial-scale=1.0,user-scalable=no,maximum-scale=1" media="(device-height: 568px)")
    %meta(name='apple-mobile-web-app-capable' content='yes')
    %meta(name='apple-mobile-web-app-status-bar-style' content='translucent-black')

    %link(rel="shortcut icon" href="/assets/favicon.ico")
    %link(rel="apple-touch-icon-precomposed" href="/assets/apple-touch-icon-precomposed.png")
    %link(rel="apple-touch-icon-precomposed" sizes="57x57" href="/assets/apple-touch-icon-57x57-precomposed.png")
    %link(rel="apple-touch-icon-precomposed" sizes="72x72" href="/assets/apple-touch-icon-72x72-precomposed.png")
    %link(rel="apple-touch-icon-precomposed" sizes="114x114" href="/assets/apple-touch-icon-114x114-precomposed.png")

    = csrf_meta_tags

    / Stylesheets (Don't change include order)
    = stylesheet_link_tag 'application',
                          '//netdna.bootstrapcdn.com/font-awesome/3.2.0/css/font-awesome.min.css'

  %body.main{class: @page || 'page'}

    / Content
    #content
      = yield

    / Footer
    = render partial: 'layouts/partials/footer'

    / Google Analytics
    = render partial: 'layouts/partials/trackers'

app/views/layouts/hq/application.html.haml
!!! 5
/[if IE 8]      <html class="no-js lt-ie10 lt-ie9" lang="en-us">
/[if IE 9]      <html class="no-js lt-ie10 lt-ie9" lang="en-us">
/[if lt IE 10]  <html class="no-js lt-ie10" lang="en-us">
%html{lang: 'en', class: 'no-js'}
  %head
    %title= yield :title
    %meta(http-equiv="content-type" content="text/html" charset="utf-8")
    %meta(http-equiv="x-ua-compatible" content="ie=edge,chrome=1")
    %meta(name="description" content="")
    %meta(name="author" content="")
    %meta{content: 'initial-scale=1.0,user-scalable=no,maximum-scale=1,width=device-width', name: 'viewport'}
    %meta(name="viewport" content="initial-scale=1.0,user-scalable=no,maximum-scale=1" media="(device-height: 568px)")
    %meta(name='apple-mobile-web-app-capable' content='yes')
    %meta(name='apple-mobile-web-app-status-bar-style' content='translucent-black')

    %link(rel="shortcut icon" href="/assets/favicon.ico")
    %link(rel="apple-touch-icon-precomposed" href="/assets/apple-touch-icon-precomposed.png")
    %link(rel="apple-touch-icon-precomposed" sizes="57x57" href="/assets/apple-touch-icon-57x57-precomposed.png")
    %link(rel="apple-touch-icon-precomposed" sizes="72x72" href="/assets/apple-touch-icon-72x72-precomposed.png")
    %link(rel="apple-touch-icon-precomposed" sizes="114x114" href="/assets/apple-touch-icon-114x114-precomposed.png")

    = csrf_meta_tags

    / Stylesheets (Don't change include order)
    = stylesheet_link_tag 'hq/application',
                          '//netdna.bootstrapcdn.com/font-awesome/3.2.0/css/font-awesome.min.css'
    = yield :head

  %body.main

    / Navbar
    = render partial: 'layouts/hq/partials/navbar'

    #wrapper

      / Sidebar
      %section#sidebar
        = render partial: 'layouts/hq/partials/dock'

      / Tools
      %section#tools
        = render partial: 'layouts/hq/partials/breadcrumb'
        = render partial: 'layouts/hq/partials/toolbar'

      / Content
      #content
        = yield

    / Footer
    = render partial: 'layouts/hq/partials/footer'

    / Google Analytics
    = render partial: 'layouts/partials/trackers'

app/views/layouts/hq/base.html.haml
!!! 5
/[if IE 8]      <html class="no-js lt-ie10 lt-ie9" lang="en-us">
/[if IE 9]      <html class="no-js lt-ie10 lt-ie9" lang="en-us">
/[if lt IE 10]  <html class="no-js lt-ie10" lang="en-us">
%html{lang: 'en', class: 'no-js'}
  %head
    %title= yield :title
    %meta(http-equiv="content-type" content="text/html" charset="utf-8")
    %meta(http-equiv="x-ua-compatible" content="ie=edge,chrome=1")
    %meta(name="description" content="")
    %meta(name="author" content="")
    %meta{content: 'initial-scale=1.0,user-scalable=no,maximum-scale=1,width=device-width', name: 'viewport'}
    %meta(name="viewport" content="initial-scale=1.0,user-scalable=no,maximum-scale=1" media="(device-height: 568px)")
    %meta(name='apple-mobile-web-app-capable' content='yes')
    %meta(name='apple-mobile-web-app-status-bar-style' content='translucent-black')

    %link(rel="shortcut icon" href="/assets/images/favicon.ico")
    %link(rel="apple-touch-icon-precomposed" href="/assets/images/apple-touch-icon-precomposed.png")
    %link(rel="apple-touch-icon-precomposed" sizes="57x57" href="/assets/images/apple-touch-icon-57x57-precomposed.png")
    %link(rel="apple-touch-icon-precomposed" sizes="72x72" href="/assets/images/apple-touch-icon-72x72-precomposed.png")
    %link(rel="apple-touch-icon-precomposed" sizes="114x114" href="/assets/images/apple-touch-icon-114x114-precomposed.png")

    = csrf_meta_tags

    / Stylesheets (Don't change include order)
    = stylesheet_link_tag 'application',
                          '//netdna.bootstrapcdn.com/font-awesome/3.2.0/css/font-awesome.min.css'
    = yield :head

  %body.main{class: @page || 'page'}

    / Navbar
    = render partial: 'layouts/partials/navbar'

    #wrapper

      / Sidebar
      %section#sidebar
        = render partial: 'layouts/partials/dock'

      / Tools
      %section#tools
        = render partial: 'layouts/partials/breadcrumb'
        = render partial: 'layouts/partials/toolbar'

      / Content
      #content
        = yield

    / Footer
    = render partial: 'layouts/partials/footer'

    / Google Analytics
    = render partial: 'layouts/partials/trackers'

app/views/layouts/hq/partials/_breadcrumb.haml
%ul#breadcrumb.breadcrumb
  = render_breadcrumbs :separator => ' / '

app/views/layouts/hq/partials/_dock.haml
%i#toggle.icon-align-justify.icon-large

%ul#dock
  %li.launcher
    %i.icon-dashboard
    =link_to 'Dashboard', '/hq/dashboard.html'
  %li.launcher
    %i.icon-file-text-alt
    =link_to 'Forms', '/hq/dashboard/form.html'
  %li.launcher
    %i.icon-table
    =link_to 'Tables', '/hq/dashboard/tables.html'
  %li.launcher.dropdown.hover
    %i.icon-flag
    %a{href: '#'} Reports
    %ul.dropdown-menu
      %li.dropdown-header Launcher description
      %li
        %a{:href => '#'} Action
      %li
        %a{:href => '#'} Another action
      %li
        %a{:href => '#'} Something else here
  %li.launcher
    %i.icon-bookmark
    %a{href: '#'} Bookmarks
  %li.launcher
    %i.icon-cloud
    %a{href: '#'} Backup
  %li.launcher
    %i.icon-bug
    %a{href: '#'} Feedback

#beaker{data: {toggle: 'tooltip'}, title: 'Made by lab2023'}

app/views/layouts/hq/partials/_footer.haml
/ Javascripts
= javascript_include_tag '//cdnjs.cloudflare.com/ajax/libs/modernizr/2.6.2/modernizr.min.js',
                         'hq/application'

app/views/layouts/hq/partials/_navbar.haml
#navbar.navbar.navbar-default
  %a.navbar-brand{:href => '#'}
    %i.icon-beer
    Hierapolis
  %ul.nav.navbar-nav.pull-right
    %li.dropdown
      %a.dropdown-toggle{data: {toggle: 'dropdown'}, :href => '#'}
        %i.icon-envelope
        Messages
        %span.badge 5
        %b.caret
      %ul.dropdown-menu
        %li
          %a{:href => '#'} New message
        %li
          %a{:href => '#'} Inbox
        %li
          %a{:href => '#'} Out box
        %li
          %a{:href => '#'} Trash
    %li
      %a{href: '#'}
        %i.icon-cog
        Settings
    %li.dropdown.user
      %a.dropdown-toggle{'data-toggle' => 'dropdown', :href => '#'}
        %i.icon-user
        %strong John DOE
        =image_tag 'http://lorempixel.com/output/fashion-q-c-20-20-4.jpg', width: '20px', height: '20px', class: 'img-rounded'
        %b.caret
      %ul.dropdown-menu
        %li
          %a{:href => '#'} Edit Profile
        %li.divider
        %li
          =link_to 'Sign out', 'index.html'

app/views/layouts/hq/partials/_toolbar.haml
#toolbar
  .btn-group
    = yield :toolbar

app/views/layouts/login.haml
!!! 5
/[if IE 8]      <html class="no-js lt-ie10 lt-ie9" lang="en-us">
/[if IE 9]      <html class="no-js lt-ie10 lt-ie9" lang="en-us">
/[if lt IE 10]  <html class="no-js lt-ie10" lang="en-us">
%html{lang: 'en', class: 'no-js'}
  %head
    %title= yield :title
    %meta(http-equiv="content-type" content="text/html" charset="utf-8")
    %meta(http-equiv="x-ua-compatible" content="ie=edge,chrome=1")
    %meta(name="description" content="")
    %meta(name="author" content="")
    %meta{content: 'initial-scale=1.0,user-scalable=no,maximum-scale=1,width=device-width', name: 'viewport'}
    %meta(name="viewport" content="initial-scale=1.0,user-scalable=no,maximum-scale=1" media="(device-height: 568px)")
    %meta(name='apple-mobile-web-app-capable' content='yes')
    %meta(name='apple-mobile-web-app-status-bar-style' content='translucent-black')

    %link(rel="shortcut icon" href="/assets/images/favicon.ico")
    %link(rel="apple-touch-icon-precomposed" href="/assets/images/apple-touch-icon-precomposed.png")
    %link(rel="apple-touch-icon-precomposed" sizes="57x57" href="/assets/images/apple-touch-icon-57x57-precomposed.png")
    %link(rel="apple-touch-icon-precomposed" sizes="72x72" href="/assets/images/apple-touch-icon-72x72-precomposed.png")
    %link(rel="apple-touch-icon-precomposed" sizes="114x114" href="/assets/images/apple-touch-icon-114x114-precomposed.png")

    / Stylesheets (Don't change include order)
    = stylesheet_link_tag 'application',
                          '//netdna.bootstrapcdn.com/font-awesome/3.2.0/css/font-awesome.min.css'
    = yield :head

  %body.login

    .wrapper
      = yield

    / Footer
    = render partial: 'layouts/partials/footer'

    / Google Analytics
    = render partial: 'layouts/partials/trackers'

app/views/layouts/partials/_footer.haml
/ Javascripts
= javascript_include_tag '//ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js',
                         '//ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js',
                         '//cdnjs.cloudflare.com/ajax/libs/modernizr/2.6.2/modernizr.min.js',
                         'application'